apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-interactive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-interactive
  template:
    metadata:
      labels:
        app: elasticsearch-interactive
    spec:
      containers:
        - name: elasticsearch-interactive
          image: elasticsearch-interactive-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-interactive-service
spec:
  selector:
    app: elasticsearch-interactive
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: LoadBalancer